### ISSUE TITLE
hapi version compatibility?

### ISSUE THREAD

**Issue by cudasteve** [athieriot/grunt-hapi#59]
In the README:

> This plugin requires Grunt ~0.4.2 And is compatible with Hapi 9.3.x

In package.json:

```
  "devDependencies": {
    // ...
    "hapi": "13.4.1",
    // ...
  },
```

Could you clarify what version of hapi this is compatible with?  Thanks!

**Comment by athieriot** [comment]
Hi @cudasteve,

   I have been running the tests again newest versions of Hapi from time to time (GreenKeeper keeps me up to date)
   However I haven't been much updating the Readme that much you are right.
 
   The latest version of ```grunt-hapi``` (0.12.0) has been validated against ```Grunt 1.0``` and ```Hapi 0.13.3```.
   Please note that ```grunt-hapi``` only have ```Hapi``` as a dev dependency and nothing stops you from using it with more recent (Or older) versions.

Have you experienced any issues?

Thanks !

**Comment by cudasteve** [comment]
Well I was trying to update from hapi 8.8.1 to as current as I can.  It seems like there's been a good amount of breaking changes in the way the config file is setup, so I was running into issues.  Just sorta wanted to verify what versions grunt-hapi was expected to work with so I could rule it out of the equation.  It looks like my issues were with breaking changes in hapi, so I imagine grunt-hapi would have worked fine with version 13.  But I'm just leaving it at v8 for now.

**Comment by athieriot** [comment]
Fair enough, I hope you are going to find a solution to your issues.

If there is anything caused by ```grunt-hapi```, please let me know and I will try to fix it.

Pull Request are gladly accepted as well :)
