### ISSUE TITLE
Having trouble starting task

### ISSUE THREAD

**Issue by ivanoats** [athieriot/grunt-hapi#9]
I am following the example in the test directory, but I'm getting an error with the static route, because I already have a static route in my server (that I'd like to keep outside of grunt)

`Fatal error: Hapi ["/Users/ivan/dev/scholarships/server"] -  Error: New route /{path*} conflicts with existing /{param*}`

I have no base specified in my Gruntfile:

```javascript
    hapi: {
      development: {
        options: {
          server: require('path').resolve('./server')
        }
      }
    },
```

If I comment out line 18 in tasks/hapi.js it does work fine...
https://github.com/athieriot/grunt-hapi/blob/master/tasks/hapi.js#L18

Do we need a better way to merge the options? Lodash _.defaults ?

**Comment by ivanoats** [comment]
`bases: {}` works great.

**Comment by athieriot** [comment]
Hi ivan,

   Today, another person complained about the default value of the ```bases``` option so it was probably better to change the default value.

   I switched the major version number so it shouldn't bother anyone but if you prefer, you can update to ```0.9.0``` to use the plugin properly.

Thank you again
